### ISSUE TITLE
fail build with kernel +5.8

### ISSUE THREAD

**Issue by sl1pkn07** [barrybingo/exfat-nofuse#5]
~~~
make -C /usr/lib/modules/5.8.12-arch1-1/build M=/var/lib/dkms/exfat/206.297a573/build modules
make[1]: se entra en el directorio '/usr/lib/modules/5.8.12-arch1-1/build'
  CC [M]  /var/lib/dkms/exfat/206.297a573/build/exfat_core.o
  CC [M]  /var/lib/dkms/exfat/206.297a573/build/exfat_super.o
/var/lib/dkms/exfat/206.297a573/build/exfat_super.c: En la función ‘exfat_readpages’:
/var/lib/dkms/exfat/206.297a573/build/exfat_super.c:1635:9: error: declaración implícita de la función ‘mpage_readpages’; ¿quiso decir ‘mpage_readpage’? [-Werror=implicit-function-declaration]
 1635 |  ret =  mpage_readpages(mapping, pages, nr_pages, exfat_get_block);
      |         ^~~~~~~~~~~~~~~
      |         mpage_readpage
cc1: algunos avisos se tratan como errores
make[2]: *** [scripts/Makefile.build:281: /var/lib/dkms/exfat/206.297a573/build/exfat_super.o] Error 1
make[1]: *** [Makefile:1752: /var/lib/dkms/exfat/206.297a573/build] Error 2
make[1]: se sale del directorio '/usr/lib/modules/5.8.12-arch1-1/build'
make: *** [Makefile:35: all] Error 2
~~~

**Comment by barrybingo** [comment]
Ok I put a couple of patches into a new branch for you to try [new-kernel-patches](https://github.com/barrybingo/exfat-nofuse/tree/new-kernel-patches)

I took the mpage_readpages from [here](https://github.com/namjaejeon/linux-exfat-oot/commit/b457fd79f980b82c99878edd0240d823a6a520ce)

and get_seconds was removed for y2038 so now using ktime_get_real_seconds

**Comment by sl1pkn07** [comment]
Hi

seems build, install and use as expected

greetings!
